apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/programmer-my/jellyfin-helm.git
    targetRevision: dev
    path: .
    helm:
      valueFiles:
        - values.yaml
      values: |
        jellyfin:
          image: linuxserver/jellyfin:10.11.11
          env:
            - name: TZ
              value: "Asia/Kuala_Lumpur"
            - name: JELLYFIN_PublishedServerUrl
              value: "http://192.168.100.12"
        loadBalancers:
          server:
            port: 80
            targetPort: 8096
        extraMounts:
          - name: media
            mountPath: /media
            volume:
              nfs:
                server: 192.168.0.137
                path: /tank/media
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin-staging
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /metadata/labels
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
