apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/programmer-my/jellyfin-helm.git
    targetRevision: dev
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin-staging
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
